inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'Gemfile'
    - 'acts_as_follower.gemspec'
    - 'test/dummy30/**/*'
  UseCache: true
  SuggestExtensions: false
  NewCops: enable

#
# *** Layout
#
Layout/LineLength:
  Max: 120

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space

#
# *** Metrics
#
Metrics/AbcSize:
  Max: 27

Metrics/BlockLength:
  Max: 35
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 150

Metrics/ParameterLists:
  Max: 4

Metrics/PerceivedComplexity:
  Max: 10

#
# *** Naming
#
Naming/VariableNumber:
  EnforcedStyle: snake_case

Naming/MethodParameterName:
  Enabled: false
#
# *** Style
#
Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false
